### ISSUE TITLE
wildcard with subdomain

### ISSUE THREAD

**Issue by ruben-herold** [silkeh/pdns_api.sh#31]
hi,

I'm using current version  and try to add a wildcard cerificate:

domains.txt:

*.test.sub.domain.de test.sub.domain.de > start_test.sub.domain.de

In powerdns we have two zones:

domains.de and sub.domain.de

The script  add the records to domai.de instead of sub.domain.de, so the validation failed

**Comment by silkeh** [comment]
Thanks for reporting this. It turns out that the zones would not be sorted properly when retrieved from the API.
I have pushed a set of commits to [this branch](https://github.com/silkeh/pdns_api.sh/tree/fix-zone-retrieval) that should resolve the issue. Please let me know if that resolves the issue for you.

**Comment by ruben-herold** [comment]
Thx for the fast response. Seems to work now. All my tests run fine!!

**Comment by silkeh** [comment]
Great! I have just released [v0.5.1](https://github.com/silkeh/pdns_api.sh/releases/tag/v0.5.1 ) with the fix.
