### ISSUE TITLE
Increment serial number of SOA entry

### ISSUE THREAD

**Issue by zilon84** [silkeh/pdns_api.sh#7]
As far as I observed the behavior of this nice hook, the serial nuber (or ID) of the domain is not modified or incremented and thus slaves don't know that any changes were made or the challenges added.

**Comment by zilon84** [comment]
Referring to http://jpmens.net/2015/01/09/a-look-at-the-powerdns-rest-api/

The  domainmetadata table has to be altered and for each domain an antry of the shape

+----+-----------+--------------+---------------------+
| id | domain_id | kind         | content             |
+----+-----------+--------------+---------------------+
|  1 |         6 | SOA-EDIT-API | INCEPTION-INCREMENT |
+----+-----------+--------------+---------------------+

has to be made. This automatically increase the ID of the SOA entry.

**Comment by silkeh** [comment]
The script does not do this because it should be done through SOA-EDIT-API.
It is not necessary to set this in the database, it is possible to use the API or command line to set it:

    pdnsutil set-meta [zone] SOA-EDIT-API INCEPTION-INCREMENT

What the script could do is output a warning if it is not set (or set it to a default value like `INCEPTION INCREMENT`).
